- prober/prober.go
Fixes bug where if DisableJitter=true, then Prober.Start will exit prematurely.
> Allow DisableJitter=true and the use of the gRPC service to add probes.

- go.mod
- go.sum
The current version has a vulnerability (CVE-2020-29652) present in the `golang.org/x/crypto` library. Updating this library fix the security issue.
> Bump golang.org/x/crypto to fix cve-2020-29652

- cloudprober.go
- cloudprober_test.go
- config/runconfig/runconfig.go
- go.sum
This is most useful for tests in which a full cloudprober is
required. Each test initializes a new instance, calling
InitFromConfig and Start and when the context passed to Start is done,
the cloud prober instance will shut down fully. There is currently no
good way to ensure that the last instance has shut down before starting
a new one, so I used a time.Sleep.
- Added ClearDefaultGRPCServer() to runconfig to clear the saved gRPC
server
- On context close, Start will fully clean up the global variables found
in cloudprober.go
- Added test that starts CloudProber, stops it, and starts it again.
Before this code change, that would have always failed with the second
config ignored.
> Allow multiple instances of cloudprober to run sequentially.

- surfacers/stackdriver/stackdriver.go
= monitoring.New is deprecated.
> [strackdriver] Use NewService instead of New.

- metrics/dist_test.go
Noticed a typo in line 44 of your test, "distrubtion => distribution"
Little help, but I thought it would still be welcomed 🙂
> Fixed typo in error message

- docs/themes/hugo-material-docs/layouts/partials/header.html
Website header should always be Cloudprober. Page title is anyway shown below.
> Pin website header title to Cloudprober.

- Makefile
= Add -s -w to linker flags
= Factor out LDFLAGS.
> [Makefile] Strip production binaries of debug symbols.

- probes/http/http.go
- probes/http/http_test.go
Use different HTTP transports/clients for running requests within a probe cycle.
> HTTP Probe: Make connections behavior more deterministic.

- examples/additional_label/cloudprober.cfg
- probes/http/http.go
- probes/http/request.go
- probes/options/labels.go
- probes/proto/config.proto
Tested this change with the following config:
```
probe {
type: HTTP
name: "http_test"
targets {
host_names: "localhost:3141,www.google.com:80"
}
additional_label {
key: "server-addr"
value: "@target.ip@:@target.port@"
}
http_probe {
resolve_first: true
}
}
server {
type: HTTP
}
```
and got results like this:
```
cloudprober 1644744713276298452 1644744769 labels=ptype=http,probe=http_test,dst=www.google.com,server-addr=172.217.1.228:80 total=28 success=28 latency=2383530.500 timeouts=0 resp-code=map:code,200:28
cloudprober 1644744713276298453 1644744773 labels=ptype=http,probe=http_test,dst=localhost,server-addr=127.0.0.1:3141 total=30 success=30 latency=26085.200 timeouts=0 resp-code=map:code,200:30
```
^ Note the IP in the server-addr label.
> Add the ability to add target IP to labels.

- probes/http/request.go
- probes/options/labels.go
- probes/options/labels_test.go
- probes/ping/ping.go
This change enhances the logic of the additional label: `@target.port@`.  So far, we've been using only the port available in the target's specification. After this change, we'll use probe's port if available.
> Consider probe's port for the additional label.

- probes/udp/udp.go
= Use target's port if it's not configured in the probe. This is what all other probe types do.
= Resolve target outside of the runSingleProbe function, which runs for every source port.
= Add support for IP and port additional labels.
> Improve UDP probe.

- probes/http/http.go
- probes/http/http_test.go
- probes/http/request.go
* Fix a bug where we were not really refreshing bearer token in HTTP request (#93).
* Stop storing OAuth bearer token in probe's state, and stop updating it in the target refresh loop. This may create concurrency issues.
* Instead of the above, get a new token before making the HTTP request. Note that most OAuth token sources already implement caching so it should be okay.
> Fix a bug in OAuth handling.

- surfacers/probestatus/dashboard.go
- surfacers/probestatus/dashboard_test.go
- surfacers/probestatus/probestatus.go
= Select durations based on timeseries size and resolution.
= Improve formatting (use 3d instead of 72h).
= Add more tests.
> [probestatus] Make dashboard durations flexible.

- sysvars/sysvars.go
- sysvars/sysvars_ec2.go
- sysvars/sysvars_test.go
* Don't wait too long for EC2 metadata if we are not explicitly looking for EC2 metadata (--cloud_metadata=ec2 is not set).
* This improves the startup speed on non-EC2 machines by up to 6s.
> [startup] Improve Cloudprober startup time.

- docs/content/concepts/probe.md
- probes/http/http.go
This PR adds a very simple pass at exposing the x509 peer certificate expiry in seconds as a metric, as defined in issue #119 
```
cloudprober 1653310360629045004 1653310377 labels=ptype=http,probe=google_homepage,dst=www.google.com total=4 success=4 latency=467677.880 timeouts=0 resp-code=map:code,200:4 ssl_expiration_seconds=5633226
cloudprober 1653310360629045008 1653310387 labels=ptype=http,probe=google_homepage,dst=www.google.com total=6 success=6 latency=704211.588 timeouts=0 resp-code=map:code,200:6 ssl_expiration_seconds=5633216
```
> add a simple certificate expiry metric

- rds/client/client.go
This has been causing log spam for file based targets.
> [RDS client] Don't "Info" log if state has not changed.

- probes/http/request.go
This avoids Transfer-Encoding: chunked, which the Go HTTP client
otherwise adds for us by default because it can't figure out the length
of the body.
Chunked transfer encoding is harder to handle on some servers, e.g.
wsgi+Django. It's also pretty unnecessary when we actually know the
exact length of the body in advance.
> Set Content-Length header on outgoing requests

- rds/kubernetes/ingresses.go
- rds/kubernetes/testdata/ingresses.json
Hello all, as you know networking.k8s.io/v1beta1 API version of Ingress is no longer served as of v1.22 k8s version. Therefore Cloudprober fails to list the available ingress targets. 
```
client.go:72] [cloudprober.rds-server] kubernetes.client: getting URL: https://100.64.0.1:443/apis/networking.k8s.io/v1beta1/ingresses
ingresses.go:196] [cloudprober.rds-server] ingressesLister.expand(): error while getting ingresses list from API: HTTP response status code: 404, status: 404 Not Found
```
Can we please merge this change and cut a release to fix the issue. We are not able to use Cloudprober after our upgrade to v1.22.
> Migrate ingresses from v1beta1 to v1 API

- probes/http/http.go
The repeated calls to clientsForTarget are generating new clients at every probing interval, which effectively makes the keep alive option useless (a new connection is created for every new client). Pulling that function call out of the loop and storing a single client list (one client per request) allows keep alive to function as normal again.
> Move clientsForTarget call out of probing loop.

- probes/http/http.go
There is a difference between nil interface and interface pointing to a nil value. My earlier fix in #223 was checking for interface being nil (that condition was never met), while we had to check for interface pointing to a nil value.
> [probes.http] Really fix the nil config problem (#219)

- logger/logger.go
Added a custom label option in cloudprober's logger.go file for having custom labels in cloud logger entries. Currently we are logging all error message and details in cloud logger and these logs are needed for better debugging experience. And there is no way to get any particular log, so, a probe_id is generated and we need this probe_id in the labels of log entry, so, that we can search any particular log. 
Screenshot of cloud logger after using label option is attached.
> Added custom labels option for cloud log entries

- common/metadata/metadata.go
- common/metadata/metadata_test.go
- logger/logger.go
- surfacers/stackdriver/resource.go
See #257 for the background.
Cloud Run starts/restarts the container multiple with the same revision id. This creates a problem for the Stackdriver metrics (at least in the short term) as for the cumulative metrics, a point's startTime is tied to the Cloudprober start time and its endTime cannot be before the startTime. This condition is violated if there are multiple processes exporting data to the same resource.
> [surfacers.stackdriver] Use random task ID for Google Cloud Run.

- common/oauth/bearer.go
- common/oauth/bearer_test.go
- rds/kubernetes/client.go
- rds/kubernetes/client_test.go
* Kubernetes version [1.21.14](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume) introduced the option of expiring/rotating tokens.
* Kubernetes automatically refreshes the locally mounted token file. This PR configures RDS' k8s client to reload the token from the file on a regular basis (every minute).
* This is similar to what client-go library does (see: https://github.com/cloudprober/cloudprober/issues/283#issuecomment-1441114178).
> [rds.k8s] Refresh in-cluster token every minute

- probes/http/http.go
> [probes.http] Don't overwrite server_name if set in tls_config

- probes/common/sched/sched.go
- probes/common/sched/sched_test.go
This is a relatively new probe, probably not being used by many yet. Overall probe works but it'll end up creating endless recursion I believe.
> [probes.tcp] Fix a bug in TCP probe scheduler

- cloudprober.go
- cmd/cloudprober.go
* These URLs got removed when we moved to a custom http.ServerMux to implement the probe status UI.
* They can be disabled by setting the environment variable: CLOUDPROBER_DISABLE_HTTP_PPROF.
> [debug] Add back debug pprof URLs.

- probes/common/sched/sched.go
- probes/common/statskeeper/statskeeper.go
- probes/dns/dns.go
- probes/external/external.go
- probes/grpc/grpc.go
- probes/http/http.go
- probes/http/request.go
- probes/options/labels.go
- probes/options/labels_test.go
- probes/ping/ping.go
- probes/tcp/tcp.go
- probes/udp/udp.go
- probes/udplistener/udplistener.go
This bug gets triggered if you're using additional_label with targets that have same name (but different labels or ports) within a probe, e.g. "host_names: www.google.com:80,www.google.com:443".
Additional labels will get mixed up if you've different targets with the same name because so far we were using only target names to maintain additional labels.
To fix this issue, use the same endpoint.Key() function while updating labels for the targets and retrieving them. In all the probes use a consistent argument for AdditionalLabel functions.
Also, add a wiki page about current status of additional labels (that I found while working this bug):
https://github.com/cloudprober/cloudprober/wiki/Additional-Labels-Rollout-Status
> [labels] Fix a bug in additional labels processing.

- probes/external/external.go
- probes/external/external_test.go
- probes/external/runcmd_linux.go
- probes/external/runcmd_nonlinux.go
This PR addresses #299.
`runCommandFunc` and `runCommand` function return stderr from a command by default.
> Output stderr from a command by default when running external probe with once mode

- common/oauth/http_token.go
We were using a buffered reader for the HTTP body, which meant that once
the request body is read, it will be empty unless we reset it.
Currently using the same type of reader as the one used in the
probes/http package. I'll eventually move this to a common package.
> [oauth] Fix a bug in http_token.

- logger/logger.go
- probes/http/http.go
- probes/http/request.go
- probes/http/request_test.go
* My past PR introduced a bug where the request body was not
not if we were using oauth token source "and" body was too large.
* Add tests to catch this scenario.
* While here, fix a small bug in Logger.Debug().
> [probes.http] Fix a bug in prepareRequest.

- common/httputils/httputils.go
- common/httputils/httputils_test.go
- common/oauth/http_token.go
- probes/http/request.go
- probes/http/request_test.go
Redirects with data don't work if GetBody is not set.
Ref: This is the net/http.Client code that disables redirect for data + 307:
https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/net/http/client.go;l=522
> [http] Set request's GetBody explicitly to make redirect work.

- probes/external/external.go
- probes/external/external_test.go
It catches the issue reported in #395. This also increases the code coverage from 71.4% to 79.8%
--        github.com/cloudprober/cloudprober/probes/external      coverage: 71.4% of statements
++       github.com/cloudprober/cloudprober/probes/external      coverage: 79.8% of statements
> [probes.external] Add test for startCmdIfNotRunning.

- probes/external/external_test.go
- Verify that we restart the command when it stops (pause=0).
> [probes.external] Improve the startCmdIfNotRunning test further.

- common/httputils/httputils.go
- common/httputils/httputils_test.go
- probes/http/request.go
- probes/http/request_test.go
= Currently all probes with request body are broken. See the bug report https://github.com/cloudprober/cloudprober/issues/407 for more details. = Looking at Go's internal code for HTTP transport and transfer, it's pretty clear that anything other than a dedicated buffered reader will not work for request body.
= During data transfer over the connection, transfer tries to read the body again after reading for the content-length and even after receiving
EOF in the first read. This is probably a bug in Go: it's reasonable to
see if there is more to be read, but I think it should not ignore the
first EOF.
= This bug has existed since Cloudprober version v0.11.9 when we added Content-Length header: https://github.com/cloudprober/cloudprober/pull/168 = I'll add tests in the follow up PRs to …
> [probes.http] Fix HTTP request body handling.

- probes/http/request.go
- probes/http/request_test.go
Hi,
I wanted to add HTTP headers to a probe configuration and I found the "header" option first, as well as a "headers" option which appeared to be the deprecated equivalent (if I'm understanding correctly).
Adding headers to the "header" option seemed to have no effect, it appears only "headers" is being checked. This should resolve that.
Hopefully this is correct. It seems to work for me :)
> [probes.http] Include headers configured with `header` option in requests

- common/oauth/http_token.go
- common/oauth/http_token_test.go
* While fixing the HTTP request body handling in #408, I introduced a bug: that PR changed request body to be buffered all the time to simplify it. I missed changing oauth2.http_token at that time. This PR fixes that.
* Improve tests.
> [oauth2] Fix a bug in HTTP token refresh.

- cloudprober.go
- surfacers/probestatus/probestatus.go
It gets activated after Cloudprober has fully started. It can be used for readiness and liveness probes.
> Add a health handler.

- common/tlsconfig/tlsconfig.go
- common/tlsconfig/tlsconfig_test.go
Much thanks to @cbroglie for catching this bug in #428.
> [tls] Don't return before setting the servername.

- probes/dns/dns.go
- probes/external/external.go
- probes/http/http.go
- probes/ping/ping.go
- probes/tcp/tcp.go
One possible repercussion of this could be increased memory allocation and de-allocations for large number of probes/targets. Rough calculation for the record:
* Based on the map cloning [benchmark](https://github.com/cloudprober/cloudprober/blob/83add1a5e02d2714d71a10b7cb3ed42d8bf27009/metrics/map_test.go#L160), each map clone causes N+6 allocations where N is number of keys. Assuming each resp-code entry takes about 24 bytes (8 byte for keys array, 16 bytes for key-value map entry) and there can be say 10 resp-code in the map, and taking into account some static overhead, we're looking at around 300 bytes per resp-code map cloning.
* Latency distribution requires explicit configuration so it's less common. As per benchmark, distribution cloning requires fixed number of allocation (4), …
> [metrics] Clone latency and other similar metrics

- prober/prober.go
* This check is wasteful. Eventmetrics to String conversion is not cheap.
* This is the commit that introduced this check: https://github.com/cloudprober/cloudprober/commit/b1147ad723a2bedf6ba441717b95212a44907e4f
* Here is more context on this check:
https://github.com/cloudprober/cloudprober/blob/33b78ba5b89953a0bea4d38f8cd5f0c8cfb8e858/logger/logger.go#L69
(Note: I think it's okay to continue to check logs for really big lines as there is nothing wasteful there)
> [metrics] Remove (now) unnecessary metric size check.

- docs/content/docs/how-to/extensions.md
- examples/extensions/myprober/myprobe/myprobe.go
- metrics/dist.go
- metrics/eventmetrics_test.go
- metrics/float.go
- metrics/int.go
- metrics/map.go
- metrics/metrics.go
- metrics/string.go
- probes/common/statskeeper/statskeeper_test.go
- probes/dns/dns.go
- probes/external/external.go
- probes/grpc/grpc.go
- probes/http/http.go
- probes/ping/ping.go
- probes/tcp/tcp.go
- probes/udp/udp.go
- probes/udplistener/udplistener.go
Changes:
* Remove `AddInt64` and `AddFloat64` from the Value interface. This lets us clean up all the implementations.
* Introduce a new interface type LatencyValue that supports the Values interface and `AddFloat64()`. Only Float and Distribution types need to meet this interface. As the name says, this interface will be used for latency values.
* Remove `Inc` and `IncBy` from the NumValue interface. Only "Int" type needs to support these methods.
* Add CloneDist method to Distribution type and use that instead of generic Clone() method that returns a Value.
> [metrics.latency] Add a new value type LatencyValue

- docs/content/docs/how-to/k8s_targets.md
- docs/content/docs/how-to/run-on-kubernetes.md
- docs/content/docs/how-to/targets/index.md
- docs/content/docs/overview/cloudprober/index.md
- Reduce duplication of the K8s targets content. Within the running on K8s page, link to the K8s targets page, instead of duplicating it.
- Change the overview page's first paragraph a bit to make it less dense.
> [website] A few fixes to the website.

- probes/grpc/grpc.go
- probes/grpc/grpc_xds.go
* gRPC XDS is not used widely, but if you really need it you can enable it by building cloudprober with the `-tags grpc_xds` flag.
* This reduces cloudprober binary file size by 25% (41M -> 31M). I think it's criminal for a package to add that much to the binary size.
> [probes.grpc] Disable gRPC XDS support by default.

- probes/alerting/notifier/pagerduty/pagerduty.go
- probes/alerting/notifier/pagerduty/pagerduty_test.go
- probes/alerting/proto/config.pb.go
- probes/alerting/proto/config.proto
- probes/alerting/proto/config_proto_gen.cue
This PR changes the order of precedence for the routing key, evaluating the user supplied key in the configuration, and then falling back to the env var.
I was writing the slack integration and realized that the order of evaluation didn't follow the normal standards, and I wanted to make the Slack notifications as like for like as PagerDuty notifications as possible.
> Make the order of evaluation logical for routing key

- logger/logger.go
- logger/logger_test.go
A log line like the following:
```
{"time":"2023-08-22T18:14:07.77109-07:00","level":"INFO","source":{"function":"github.com/cloudprober/cloudprober/prober.(*Prober).addProbe","file":"/home/runner/work/cloudprober/cloudprober/prober/prober.go","line":112},"msg":"Creating a HTTP probe: api_server","system":"cloudprober","component":"global"}
```
changes to:
```
{"time":"2023-08-22T18:14:07.77109-07:00","level":"INFO","source":{"function":"prober.(*Prober).addProbe","file":"prober/prober.go","line":112},"msg":"Creating a HTTP probe: api_server","system":"cloudprober","component":"global"}
```
> [logger] Trim base paths from file and function names

- config/config_tmpl.go
When utilizing Cloudprober's Go template component to generate configuration files, a scenario arose in which I required the capability to divide a pre-defined string into a slice of strings. Regrettably, the absence of a suitable macro impeded this process. As a solution, I have introduced the `stringSplit` macro, which seamlessly employs the `strings.Split()` function to accomplish this task.
> Adding the stringSplit macro to the Go template component

- docs/static/configdoc.js
Since textpb format is what most of the existing Cloudprober users must be using, it makes sense to use "textpb" as the default config language for documentation.
> [docs] Change default config language to textpb.

- docs/static/configdoc.js
Scroll to the selected heading after config doc div is processed.
> [docs] Fix one more quirk of Firefox.

- logger/logger.go
Add flag to override the GCP logging endpoint.
> Add flag to set GCP logging endpoint.

- cloudprober.go
- config/config.go
- config/config_test.go
- config/config_tmpl.go
- config/config_tmpl_test.go
- web/resources/header.go
- web/web.go
- Provide an option to specify secret environment variables, using envSecret keyword.
- When such variables are present, /config-running will be automatically disabled.
- Add another page /config-parsed that shows the parsed config and makes it clear which variables are secret.
> [config] Provide a way to hide secret environment variables.

- targets/endpoint/endpoint.go
- targets/endpoint/endpoint_test.go
HTTP probes use endpoint key as identifier to decide when to recreate probes. During VM recreations, it is possible for VM name to stay the same but VM IP changes. By adding IP to key, we ensure that in such cases, HTTP probes are recreated.
> [bugfix] Add IP to endpoint key. (#535)

- config/config_test.go
- logger/logger.go
- logger/logger_test.go
- probes/options/options_test.go
- Rename old New function to NewLegacy. This function is now deprecated.
- Add a new, simpler, New function that takes only optional arguments.
> [logger] Streamline logger interface.

- probes/alerting/alerting.go
- probes/alerting/notifier/notifier.go
- probes/alerting/notifier/notifier_test.go
Also remove duplicate template constant in alerting.go.
> [alerting] Add target ip to available alert fields.

- config/config.go
- web/web.go
Fix a bug in the functionality introduced recently in https://github.com/cloudprober/cloudprober/pull/536. We were using wrong criteria to determine if we should serve /config-running.
> [config] Fix a bug in the /config-running disabling functiionality.

- logger/logger.go
- logger/logger_test.go
- Remove unused `labels` field. We don't really need it or use it.
- Remove `log` method. We pretty much don't need it.
- Support debug log flags for nil logger.
- Have GCP logs receive the same message as the local logger.
- Add more tests.
> [logger] Simplify logger further

- probes/alerting/alerting.go
- probes/alerting/alerting_status.go
- probes/alerting/alerting_status_test.go
- probes/alerting/notifier/notifier.go
- probes/alerting/notifier/notifier_test.go
- Streamline state implementation because we'll need it to retrieve alert information while sending resolve notification.
> [alerting] Start laying foundation for resolve notifications

- probes/options/options.go
- probes/options/options_test.go
- No probe types, except for UDP, support starting a new probe before the previous one has finished.
- UDP probe's implementation to support this behavior is quite complicated and I wouldn't want to repeat it for other probe types.
> [probes] Return an error if interval is smaller than timeout

- probes/alerting/alerting.go
- probes/alerting/notifier/notifier.go
- probes/alerting/notifier/pagerduty/event_v2.go
- probes/alerting/notifier/pagerduty/pagerduty.go
- probes/alerting/notifier/pagerduty/pagerduty_test.go
- Also, instead of aggregating errors from notifiers and then logging,
log them right away and don't return errors.
- Include pagerDuty response in the error message in case of an error.
> [alerting] Fix PagerDuty resolve request creation.

- docs/content/docs/how-to/alerting/index.md
- probes/alerting/alertinfo/alertinfo.go
- probes/alerting/alertinfo/alertinfo_test.go
- probes/alerting/alerting.go
- probes/alerting/alerting_status.go
- probes/alerting/alerting_status_test.go
- probes/alerting/alerting_test.go
- probes/alerting/notifier/notifier_test.go
- probes/alerting/notifier/opsgenie/api.go
- probes/alerting/notifier/opsgenie/api_test.go
- probes/alerting/notifier/opsgenie/opsgenie_test.go
- probes/alerting/notifier/pagerduty/event_v2.go
- probes/alerting/notifier/pagerduty/pagerduty_test.go
- Instead use probe, alert, target info to create a unique de-duplication key, to be used by systems that support de-duplication.
> [alerting] Kill the concept of condition id as it's defined today

- cloudprober.go
- cmd/cloudprober.go
- config/config.go
- config/config_test.go
- config/config_tmpl.go
- config/config_tmpl_test.go
- config/configsource.go
- config/configsource_test.go
- config/testdata/cloudprober_base.cfg
- docs/content/docs/how-to/extensions.md
- examples/extensions/myprober/myprober.go
It kills a bunch of duplication. --configtest and --dumpconfig now use the same code for loading the file as rest of the regular functionality.
> [config] Simplify and streamline config handling code

- probes/ping/ping.go
When have higher number of targets (seen on 600+), no matter in single
probe or in different probes, we may cause network buffer overflow as
we add packets to the buffer much faster than NIC can handle them.
To avoid this we may increase net.core.wmem sysctl, or add 1 milisecond
dalay between buffer writes (which is done by this patch). This allows
to have stable results for even 2k targets in single probe.
Also patch improves logging
- Added debug log when probe is started.
- Do not print duplicate p.name as it is always added by logger,
add p.runCnt instead
- Improve debug message for a case when packet does not match runId
this is usually happening when we received packet after probe timeout.
> Use network buffer less aggressive in ping probe

- docs/content/docs/surfacers/overview.md
- surfacers/internal/bigquery/bigquery.go
- surfacers/internal/common/options/options.go
- surfacers/internal/common/options/options_test.go
- surfacers/internal/datadog/datadog.go
- surfacers/internal/otel/otel.go
- surfacers/internal/postgres/postgres.go
- surfacers/internal/postgres/postgres_test.go
- surfacers/proto/config.pb.go
- surfacers/proto/config.proto
- surfacers/proto/config_proto_gen.cue
- Enable add_failure_metric for all surfacers except FILE and PUBSUB.
- Add enable/disable metrics by name functionality to all surfacers
except FILE and PUBSUB.
- Update documentation to include the OpenTelemetry option.
> [surfacers] Cleanup surfacers options.

- surfacers/internal/otel/otel.go
- Container ID is a super long string and is not very useful.
- Pod info is available as host name on k8s.
> [surfacers.otel] Change resource attributes.

- .gitignore
Currently, gitignore is ignoring some root files that don't have extensions. This causes weird behavior since there are ignored files currently in the repo state.
> gitignore: unignore checked-in files without extensions

- internal/servers/http/http.go
- internal/servers/http/http_test.go
- For /lameduck and /healthcheck return "unknown" if lameduck lister is not initialized. 
- We don't want to generate log every time as that will be very noisy. One can still debug why they are getting "unknown".
> [servers.http] Fix /healthcheck when lameduck lister is not initialized.

- internal/tlsconfig/tlsconfig.go
- internal/tlsconfig/tlsconfig_test.go
Since cloudprober is the client, the dynamic cert loading needs to be implemented in GetClientCertificate rather than GetCertificate.
> Fix client cert handling when cert reloading is enabled

- probes/external/external.go
- probes/external/external_server.go
- probes/external/external_server_test.go
- probes/external/external_test.go
- probes/external/serverutils/serverutils.go
- probes/external/serverutils/serverutils_test.go
Changes:
* Split out server handling code into a different file
* Write tests for serverutils
* Use context to cancel various loops, but we'll still not be able to cancel the pending `read`.
> [probes.external] Refactor the external probe code

- surfacers/internal/postgres/postgres.go
- surfacers/surfacers.go
Hello,
during the initialisation of postgres surfacer options are never set but are later on used to check if metrics should be sent to Postgres database.
I added the options as a parameter of creating postgres surfacer.
> Postgres surfacer metric filter bugfix

- probes/external/external.go
- Use scanner.Text() to get the text of the line, instead of scanner.Bytes() as scanner.Bytes() returns the reference to the same underlying array everytime.
- We anyway convert byte array to a string while processing the line.
> [probes.external] Fix stdout streaming.

- probes/external/external_test.go
- This is important for Windows tests where deleting the test binary fails if it's still executing (for testing external probe process).
> [probes.external] Test: Kill all started processes before exiting.

- surfacers/internal/prometheus/prometheus.go
- surfacers/internal/prometheus/prometheus_test.go
- surfacers/internal/prometheus/proto/config.pb.go
- surfacers/internal/prometheus/proto/config.proto
- surfacers/internal/prometheus/proto/config_proto_gen.cue
- Add a new flag `--prometheus_metrics_prefix` to set metrics prefix for the prometheus surfacer.
- In a typical multi-tenant deployment, one would want to set metrics prefix for all tenants. Since configs are usually tenant specific, configs are not a good place for that, while binary flags are usually controlled by the operator, making them a good place for such settings.
> [surfacers.prometheus] Allow configuring metrics prefix through a flag.

- probes/external/external.go
= While reading external process's stdout and stderr, don't log the error if it's caused by pipe closing.
> [probes.external] Fix sporadic pipe read error logs.

- probes/external/serverutils/serverutils.go
We should not be writing to buffered stdout and stderr. This change was introduced recently in v0.13.4:
github.com/cloudprober/cloudprober/pull/695
> [probes.external] Fix serverutils.

- surfacers/surfacers.go
- Most folks don't add surfacers, relying on default configuration which adds `FILE` and `PROMETHEUS` surfacers. `FILE` surfacer metrics go to stdout by default, intermixing with the logs.
- Sysvars metrics are generated every 30s, producing 4 lines (for 4 eventmetrics) every 30s. This can get pretty noisy.
- This change disables sysvars metrics only for the config added by default. It will have no impact if you add `FILE` surfacer explicitly.
> [surfacers] Ignore sysvars metrics for file surfacer added by default

- targets/resolver/resolver.go
- targets/resolver/resolver_test.go
If refresh from backend fails, we should attempt to refresh on each resolve call.
Also, use read-write mutex instead of default mutex wherever possible. It won't have much impact on performance as we never lock for long, but it is still a good practice.
> [targets.resolver] On failure, attempt refresh on each resolve call.

- cloudprober.go
- cmd/cloudprober/main.go
- examples/extensions/myprober/myprober.go
- web/web.go
- web/web_test.go
This will minimize the binary code even further, making creating extensions simpler.
> [web] Move web initialization to cloudprober init.

- probes/external/serverutils/serverutils.go
I noticed that https://pkg.go.dev/github.com/cloudprober/cloudprober/probes/external/serverutils#ServeContext doesn't take a context. This has been true since it was added in https://github.com/cloudprober/cloudprober/pull/695, so it looks like an oversight. This change updates the function to properly take a context (and to work with its example code.
> Use context in ServeContext.

- internal/file/gcs.go
This cl https://github.com/cloudprober/cloudprober/pull/396 breaks accessing Google Storage as path.join converts double slash into single slash
Below code returns https:/storage.googleapis.com/bbmc-cloudradar-internal-ip-only/rds/ssl/cloudprober.crt
package main
```
import (
"fmt"
"path"
)
const gcsHTTPBaseURL = "https://storage.googleapis.com"
func main() {
fmt.Printf(path.Join(gcsHTTPBaseURL, "bbmc-cloudradar-internal-ip-only/rds/ssl/cloudprober.crt"))
}
```
> Fixing getting the cert files form Google Storage

- README.md
- Make it consistent with cloudprober.org homepage.
- Also, old image is a bit confusing now.
> [docs] Update github homepage image

- probes/dns/dns.go
- probes/dns/dns_test.go
[probes.dns] Use the common sched package for scheduling probes.
- This will remove a lot of targets and scheduling handling from DNS probe code and make things more standardized which is super important.
> [probes.dns] Use the common sched package for scheduling.

- probes/external/external.go
- probes/external/external_test.go
- probes/external/proto/config.pb.go
- probes/external/proto/config.proto
- External probe substitution labels are applied to probe command line or probe options. These labels were added before additional labels were introduced. This PR makes them consistent.
- Add more tests and documentation.
> [probes.external] Make substitution labels consistent with additional labels

- probes/grpc/grpc.go
- probes/grpc/grpc_test.go
Use a ticker to retry connection setup.
See #814 for more details.
> [probes.grpc] Fix connection retry interval

- probes/common/sched/sched.go
- probes/options/options.go
This cloning got added in https://github.com/cloudprober/cloudprober/pull/533, when we tried to standardize handling of eventmetrics through options.RecordMetrics. It doesn't really serve any purpose as probes calling this function already provide a clean, disconnected EventMetrics.
> [metrics] Don't clone eventmetrics unnecessarily

- config/config.go
- config/config_test.go
- config/testdata/include_test/cloudprober_include.glob.txtar
This is a potential solution for #826 to enable providing a file path glob in the `include` config to pick up all files in a directory.
I also toyed with the idea of allowing absolute paths in the include config as well but left it out to keep PR in sync with the issue/summary. Something along the lines of:
```
var absPath string
if filepath.IsAbs(m[1]) {
absPath = m[1]
} else {
absPath = filepath.Join(baseDir, m[1])
}
files, err := filepath.Glob(absPath)
```
> Support file glob when including config files

- probes/dns/dns.go
Setting result's latency on each run is a leftover of  the`statskeeper` usage -- `statskeeper` did metrics aggregation on its [own](https://github.com/cloudprober/cloudprober/blob/be96965267409c4a9d87e0291ebb1160944d321f/probes/common/statskeeper/statskeeper.go#L74), so each probe run produced a new result object. We moved away from the `statskeeper` package in #800.
Fixes #835.
> [probes.dns] Don't reset latency on each run

- internal/rds/client/client_test.go
- targets/resolver/resolver.go
- targets/resolver/resolver_test.go
- Make the backend resolve function take a context, and call it with a context with timeout.
- Earlier we were handling timeouts ourselves through a goroutine because when resolver was implemented there was no LookupIP with context. New method is much better.
- Also, create a custom resolver only once, no need to create a new one on each resolve call.
> [targets.dns] Use contexts for backend resolve function

- probes/common/sched/sched.go
- probes/http/http.go
- probes/http/http_test.go
This is to reduce duplication in the scheduling code. Our. common scheduler code was anyway based on HTTP probe.
Note: there is still some duplication in the startForTarget functionality, but it's the right balance right now without making it too complicated. I'll keep thinking of ways to reduce the duplication further.
> [probes.http] Migrate HTTP probe partially to common/sched

- targets/resolver/resolver_test.go
- Call resolve multiple times in tests.
- To ensure backend gets called, sleep between calls.
> [targets.resolver] Enhance DNS resolver testing further

- targets/resolver/resolver.go
- Go's LookupIP implementation is complex (to make it efficient) and not worth it when DNS server is overridden.
- LookupIP may be buggy or less deterministic when not using system's local resolvers. I am not sure if that's the case, but I think it's okay to skip it to use a simple DNS client to do DNS queries when not using local resolvers.
Go's implementation is here:
https://github.com/golang/go/blob/ab5c22e7ed6bda79f07410c0041e020e52dc9b35/src/net/dnsclient_unix.go#L609
https://github.com/golang/go/blob/ab5c22e7ed6bda79f07410c0041e020e52dc9b35/src/net/dnsclient_unix.go#L297
> [tagets.resolver] Use explicit DNS client when DNS server is overridden

- probes/external/external.go
- probes/external/external_server_test.go
- probes/external/external_test.go
If OutputMetricOptions was unset, we were trying to set field of a nil object.
Add initialization specific tests.
> [probes.external] Fix a bug in initialization of server mode

- metrics/metrics.go
- surfacers/internal/common/transform/transform.go
- Also, in metrics, print the input if we can't parse it.
> [metrics] Set type to GAUGE when exporting metrics as GAUGE

- probes/http/http.go
- probes/http/http_test.go
To address https://github.com/cloudprober/cloudprober/issues/872
Currently if the `disable_http2` option is set to true, http probes would fail with malformed response. 
This is due to `transport.ForceAttemptHTTP2` being set to false and `transport.TLSNextProto` being set to an empty map, BUT `transport.TLSClientConfig.NextProtos` being populated with `"h2", "http/1.1"`. In other words, we wanted to disable http2, but the TLS ALPN protocols contain `h2`. This is not a valid configuration.
To prevent ALPN protocols from being populated, we shouldn't use the default http transport.
Probes with the following config are succeeding without getting malformed response.
```
probe {
name: "google"
type: HTTP
targets {
host_names: "google.com"
}
interval_msec: 5000  # 5s
timeout_msec: 5000   # 5s …
```
> [probes.http] Stop using the default http transport

- probes/common/sched/sched.go
- probes/common/sched/sched_test.go
- probes/tcp/tcp.go
Moving of HTTP probe to common scheduler in https://github.com/cloudprober/cloudprober/pull/840 introduced a bug, where we stopped honoring user provided inter-target-gap. Only HTTP and TCP probes have this config field (it was initially only in HTTP, but was copied to TCP probe).
> [probes.http] Scheduler should consider user provided gap between targets

- probes/common/command/command.go
- probes/external/external_server.go
- Export external process's logs in a dedicated field: `process_stderr`
- This allow users to further parse external process's logs.
I asked ChatGPT if Datadog can do it. It seems it can:
https://chatgpt.com/share/671304a1-9944-8005-9568-cdd058c1547c
See https://github.com/cloudprober/cloudprober/issues/893 for some background.
> [probes.external] Improve on how we export external probe process's logs

- probes/dns/dns.go
This appears to be set on other probes. Obviously the workaround is `additional_label`, so I'm not sure whether it's actually worth doing this.
> [probes.dns] Add ptype="dns" label to all DNS probe metrics by default

- go.mod
Without the patch number, I hit a "toolchain not available" error from an env where go 1.22 was installed, and this project requires 1.23, and apparently it cannot locate the toolchain.
Similar discussion in: https://github.com/golang/go/issues/62278
> Update go directive to include the patch number

- probes/http/http.go
- probes/http/http_test.go
- transport.ProxyConnectHeader.Add(..) results in a nil map assignment if transport.ProxyConnectHeader is not explicitly initialized.
- Add a test to catch this.
> [probes.http] Fix proxy connect header.

- go.mod
- Go build cache is broken in 1.23.0 as explained [here](https://github.com/actions/setup-go/issues/498).
> [build] Upgrade to Go 1.23.3

- go.mod
- go.sum
This is to close https://github.com/cloudprober/cloudprober/security/dependabot/34.
> [security] Upgrade golang.org/x/net for security

- probes/external/external.go
- probes/external/external_server.go
- probes/external/external_server_test.go
- probes/external/external_test.go
- configpb and serverpb were being imported independently because in Google internal code base corresponded to two different packages. Now that both proto files are merged, we no longer need to do that.
> [probes.external] Cleanup after config and server proto merge

- metrics/eventmetrics.go
- probes/browser/browser.go
- probes/common/sched/sched.go
- probes/common/sched/sched_test.go
- probes/dns/dns.go
- probes/grpc/grpc.go
- probes/http/http.go
- probes/http/http_test.go
- probes/options/options.go
- probes/options/options_test.go
- probes/tcp/tcp.go
This is all to support single run interface for Cloudprober probes (#969).
- Make HTTP probe use RunProbeForTarget interface. This change centralizes scheduler logic further in the scheduler package.
- Since we need to keep state across runs, change scheduler's `RunProbeForTarget` interface to pass more information through a request object, which will store "target state" across successive runs,
- Update all probes to use the new interface.
> [probes.http] Refactor http-probe:scheduler interface.

- probes/http/http_test.go
- Instead of waiting on the data channel, use metrics from the probeResult for verification. Keep one test that does old-style end-to-end test.
- Also, change tests to reflect more how `probeResult` and `targetState` get initialized.
> [probes.http] Improve HTTP tests speed.

- metrics/payload/line_metric_test.go
- metrics/payload/line_metrics.go
Instead of splitting label line at `,` and then parsing parts into key-values, do a more methodical parsing:
- Read keys until `=` and enforce prometheus validity criteria on key characters (alpha-numeric and `_`).
- For values, consider the following cases:
- If value starts with `"`, it's a quoted string and read until next `"`, while taking into account escaped characters, including a `\"`.
- If value doesn't start with `"`, it's an unquoted string. Unquoted strings can contain only alpha-numeric characters and `-`, `_`, `.` (this is to cause less surprises for existing users, in case someone is exporting domain names as values).
- Values should either end with `,` or be the last value in the line.
> [probes.external] Make payload labels parsing more robust.

- Dockerfile.dev
Was working on something else and tried to test with dev docker
```
=> ERROR [build 4/4] RUN if [[ ! -f /cloudprober ]]; then go build -o /cloudprober /cmd/cloudprober.go; fi                                                      0.1s
------
> [build 4/4] RUN if [[ ! -f /cloudprober ]]; then go build -o /cloudprober /cmd/cloudprober.go; fi:
0.113 stat /cmd/cloudprober.go: directory not found
------
1 warning found (use docker --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 4)
Dockerfile.dev:8
--------------------
6 |     WORKDIR /app
7 |     COPY . /
8 | >>> RUN if [[ ! -f /cloudprober ]]; then go build -o /cloudprober /cmd/cloudprober.go; fi 
9 |     
10 |     FROM alpine
--------------------
ERROR: failed to solve: process "/bin/sh -c if [[ ! -f …
```
> [Dockerfile][dev] fix builds

- probes/browser/artifacts.go
- probes/browser/browser.go
- probes/browser/cleanup.go
- probes/browser/cleanup_test.go
- Cleanup handler was running on the probe's output directory even when configured for the local storage.
- To solve, make cleanup handler store the directory as well that it needs to work on, instead of passing that directory at the cleanup time.
> [probes.browser] Fix bug in localstorage cleanup handler

- docs/content/docs/surfacers/overview.md
Fixing syntax for a couple of surfacer options. I tested this by applying the options using the `key = value` syntax first and confirming the pod would not start. Then I changed to `key: value` and watched the pod start without fail.
> doc: fix syntax for a couple of surfacer options

- .github/workflows/go.yml
- Makefile
- Call these rules to build static FIPS-compliant binaries for linux-amd64 and linux-arm64 in an independent job.
- We'll later use these binaries for the fips docker image.
> [build] Add makefile rules to build static fips binaries

- .github/workflows/go.yml
- Dockerfile.fips
- Makefile
- This is a proper fix for not being able to build arm64 image using `docker buildx` on github default runners, due to resources. Workaround was this: https://github.com/cloudprober/cloudprober/pull/990
- Now we build fips image the same way as non-fips image.
- Other than the builtin check in the Makefile target, you can verify that a Go binary is built with boringcrypto like this:
```
$ go version ./cloudprober-fips-linux-amd64
./cloudprober-fips-linux-amd64: go1.23.5 X:boringcrypto
```
> [build] Fix fips multiarch image

- .github/workflows/go.yml
This is based on the conversation here: https://github.com/actions/setup-go/pull/515
> [build] Set caching related GO* variables to "D:" on windows

- examples/targets/dns_options.cfg
- targets/proto/targets.pb.go
- targets/proto/targets.proto
- targets/resolver/resolver.go
- targets/resolver/resolver_test.go
adds dns-over-tls (dot) in standard `tls://<server>` notation with default port 853 unless otherwise specified as server option in dns_options
> [targets.resolver] add dns-over-tls to dns_options

- go.mod
go 1.23.6 includes a security fix: https://go.dev/doc/devel/release#go1.23.0
> [build] Upgrade Go to 1.23.6

- cloudprober.go
- cmd/cloudprober/main.go
- config/config_tmpl.go
- config/config_tmpl_test.go
- config/configsource.go
- internal/servers/grpc/grpc.go
- internal/servers/grpc/grpc_test.go
- internal/sysvars/sysvars.go
- prober/prober.go
- probes/browser/artifacts.go
- probes/browser/browser.go
- probes/browser/browser_test.go
- state/state.go
- state/state_test.go
- surfacers/internal/common/options/options.go
- surfacers/internal/common/options/options_test.go
- surfacers/surfacers_test.go
- targets/lameduck/lameduck.go
- targets/targets.go
- web/resources/header.go
- web/web.go
- web/web_test.go
- State is a more appropriate name for what this package does and we want to start using state for more things, e.g. to implement #1004.
> [state] Rename config/runconfig to state

- cloudprober.go
- prober/prober.go
- prober/prober_test.go
- prober/serviceimpl.go
- prober/serviceimpl_test.go
- Make it easier to reason about which code is protected behind locks and which code is not. Explain in comments as well.
- Make the mutex RWMutex.
- Improve SaveProbesToConfig tests.
- Add tests for startProbesWithJitter
> [prober] Refactor prober init and startup code to simplify and streamline

- logger/logger.go
- logger/logger_test.go
- targets/statictargets.go
- targets/targets.go
- targets/targets_test.go
- targets.globalResolver get initialized in `init()` which means that it will get initialized before flags are parsed, making `--disable_cloud_logging` ineffective. This PR moves globalResolver initialization out of init().
- While here, also move a bunch of stuff out of `logger`'s init.
> [logger] Fix disable_cloud_logging for global resolver

- surfacers/internal/probestatus/probestatus.go
- surfacers/internal/probestatus/proto/config.pb.go
- surfacers/internal/probestatus/proto/config.proto
- surfacers/surfacers.go
- tools/gen_pb_go.sh
- Also add a warning if this surfacer's URL is not set to /status.
- Fix protobuf code generation script to work with any directory path.
> [surfacers.probestatus] Restrict to just one proberstatus instance

- probes/udp/udp.go
- probes/udplistener/udplistener.go
Exactly like for the PR https://github.com/cloudprober/cloudprober/pull/237 but for UDP and External probing
> [probes] Initialize probe config with zero values if config is not given

- common/oauth/bearer.go
- common/oauth/oauth.go
- common/oauth/oauth_test.go
- common/oauth/proto/config.pb.go
- common/oauth/proto/config.proto
- common/oauth/tokensource.go
- common/oauth/tokensource_test.go
- probes/browser/artifacts/storage/storage_abs.go
- probes/browser/artifacts/storage/storage_gcs.go
While writing documentation for OAuth I realized OAuth config doesn't flow nicely -- more specifically, bearer_token abstraction feels unnecessary.
This PR changes that. It's moving bearer_token fields outside, under oauth_config directly. We'll still continue to support bearer_token. It's not much burden as bearer_token implementation now uses the new implementation.
Old config:
```
oauth_config {
bearer_token {
file: ..
}
}
```
New config (note: old config will still work):
```
oauth_config {
file: ..
}
```
> [common.oauth] Simplify OAuth config

- common/oauth/http_token.go
- common/oauth/http_token_test.go
- common/oauth/oauth_test.go
- common/oauth/proto/config.pb.go
- common/oauth/proto/config.proto
- common/oauth/tokencache.go
- common/oauth/tokencache_test.go
- common/oauth/tokensource.go
- common/oauth/tokensource_test.go
- probes/browser/artifacts/storage/storage_abs.go
- Merge some of the http_token logic into tokensource.go to make it more consistent with other types and reduce some duplication.
- This change also allows http_token to be refreshed at interval if `refresh_interval_sec` is explicitly given.
> [common.oauth] Streamline token refresh behavior

- probes/tcp/proto/config.pb.go
- probes/tcp/proto/config.proto
- probes/tcp/tcp.go
- probes/tcp/tcp_test.go
- Add TLS check to TCP probe by just adding `tls_handshake` to `tcp_probe`.
> [probes.tcp] Add TLS support to TCP probe

- prober/prober.go
- prober/prober_test.go
The way we spread probes is like this:
We arrange probes into interval buckets. Then:
- In each interval bucket, we spread the probes equally, i.e. we sleep for a fixed duration before starting the next probe. This gap between the probes (interProbeGap) was capped at 2s, this PR raises the cap to 1min.
- Each interval bucket is randomly spaced out from each other, but that space is capped at minimum of interval and 10s (this is also changing to 1m).
This behavior was initially introduced for high frequency native probes (<2s interval) that's why we capped inter-probe gap at 2s and interval bucket start delay at 10s. Idea was that 2s gap should be good enough for native probe types (e.g. HTTP) from performance impact point of view.
Now, with the introduction of browser probe types, this …
> [prober] Improve inter-probe wait for large interval probes

- probes/browser/artifacts/artifacts.go
- probes/browser/artifacts/storage/storage.go
- probes/browser/artifacts/storage/storage_abs.go
- probes/browser/artifacts/storage/storage_gcs.go
- probes/browser/artifacts/storage/storage_s3.go
- probes/browser/artifacts/storage/storage_test.go
- probes/browser/browser.go
- probes/browser/browser_test.go
- Playwright report is always saved in a subdirectory under the output directory, e.g. `date1/ts1/pw-report` where `date1/ts1` is the output directory for a specific run. Date and timestamp are useful, but 'pw-report' here adds an unnecessary step while accessing the report.
- This change removes this subdirectory while saving the artifacts, making report access quicker.
For example, report will now be at this path: `http://localhost:9313/artifacts/test_browser_probe/2025-04-28/1745861849606/` instead of `http://localhost:9313/artifacts/test_browser_probe/2025-04-28/1745861849606/report`
> [probes.browser] Make accessing playwright reports quicker

- probes/browser/artifacts/web/artifacts.js
- probes/browser/artifacts/web/dirs.go
- probes/browser/artifacts/web/dirs_test.go
- probes/browser/artifacts/web/template.go
- probes/browser/artifacts/web/web.go
- probes/browser/artifacts/web/web_test.go
- probes/browser/browser.go
- Add a failure marker (cloudprober_probe_failed file) to artifacts of the failed probe.
- Use this marker to identify failed artifacts in the web UI. Show test `failed` in front of failed probes' artifacts.
- Also, add the ability to show only failed probes.
- See screenshot below to get an idea.
> [probes.browser] Quickly identify artifacts for failed probes.

- probes/browser/browser.go
- probes/browser/browser_test.go
- probes/browser/proto/config.pb.go
- probes/browser/proto/config.proto
- Playwright considers test spec argument (non-option arguments) to be a regular expression, which can come as a surprise in prober setup. This PR makes `test_spec` filed in the config more deterministic. If `test_spec` doesn't contain popular regex characters: ^, $, *, +,.. we assume it to be the file name within the test directory.
- Also, provide a way to include/exclude tests based on their names and tags.
> [probes.browser] Make test matching more flexible and deterministic.

- probes/browser/browser.go
- probes/browser/browser_test.go
In some cases testDir may have symlinks to the test spec. This happens for example for k8s config maps. If you mount a config map, say at /cfg, containing a test spec say test.spec.ts, its path on the filesystem will look like the following:
```
ls -l /cfg
test.spec.ts -> ..data/test.spec.ts
```
In such cases, playwright will evaluate file path as `/cfg/..data/test.spec.ts` (note ..data itself will be a symlink so final path will be even longer). In that case, if we specify test spec as `^/cfg/test.spec.ts$` it will not match anything.
To workaround this problem, let's leave out testDir from the test spec regex. We'll use `^.*/test.spec.ts$ instead.
For posterity:
Playwright code for file matching:
https://github.com/microsoft/playwright/blob/eb5e3b37402bad85e6c2b976e1a596cca0e4f47c/packag …
> [probes.browser] Make testspec matching less sensitive to testDir path.

- go.mod
- go.sum
This addresses https://security.snyk.io/vuln/SNYK-DEBIAN13-GOLANGGOLANGXOAUTH2-8754530
> Bump golang.org/x/oauth2 to v0.30.0

- docs/content/docs/how-to/external-probe/index.md
- examples/external/cloudprober_server.cfg
I had to go looking in the code for this - added docs to the first place I looked.
Thanks (addresses https://github.com/cloudprober/cloudprober/issues/1091) !
> [docs] Add docs for how to get target to the external server probe.

- internal/rds/file/file.go
- internal/rds/file/testdata/testdata.go
- targets/file/file_test.go
For file based targets, set IP to target name if IP is not provided. This is what RDS client expects. RDS client returns an error for resolve if resource IP is not set.
We do the same for other target types too:
- For example https://github.com/cloudprober/cloudprober/blob/4798dde6e4e9e3a94d8af310298f39dfbd3aef72/internal/rds/kubernetes/services.go#L163
https://github.com/cloudprober/cloudprober/blob/4798dde6e4e9e3a94d8af310298f39dfbd3aef72/internal/rds/kubernetes/ingresses.go#L127
This fixes #1099.
> [targets.file] Set IP to target name if IP is not provided

- cloudprober.go
When the host is an IPv6 address like `::1`, simple `fmt.Sprintf()` doesn't surrround the host with brackets, while `net.JoinHostPort` produces correct result like `[::1]:80`.
> Use net.JoinHostPort to combine host and port

- probes/browser/artifacts/artifacts.go
- probes/browser/artifacts/artifacts_test.go
- probes/browser/artifacts/proto/config.pb.go
- probes/browser/artifacts/proto/config.proto
- probes/browser/proto/config.pb.go
- probes/browser/proto/config.proto
- Don't run web server on workdir.
- Discourage from setting workdir. This option can be confusing.
> [probes.browser] Simplify web server root logic

- probes/browser/browser.go
- probes/common/command/command.go
- probes/common/command/runcmd_linux.go
- probes/common/command/runcmd_nonlinux.go
- After a lot of research and testing, it's clear to me that my old implementation of zombie reaper doesn't really work. Reason is -- once child process exits, that child's children (cloudprober's grandchildren) will get reparented to `pid 1` immediately.
- Calling `wait4` on these grandchildren's pgid (-pgid) is not going to work whether cloudprober is `pid 1` or not. It should theoretically have worked when cloudprober's pid is 1 because orphaned process will get reparented to cloudprober (e.g. on docker, k8s), but I've confirmed that in practice it doesn't.
- I've changed my implementation to instead wait on pid `-1`, which basically will reap all children of cloudprober. We start one goroutine per cloudprober process that checks every minute for any children to be waited. I've …
> [probes.command] Fix zombie reaper mechanism

- probes/browser/browser.go
- probes/common/command/command.go
- probes/common/command/runcmd_linux.go
- probes/common/command/runcmd_nonlinux.go
This reverts #1130, #1131.
Unfortunately my last attempt at zombie cleanup also doesn't work. This time problem is with the mutex -- when zombieReaper is waiting on the write lock it will block even the read lock acquisition, thus blocking further runCommand executions. I thought of other alternatives but I think trying to manage this out is not worth it.
For the zombie leak problem in docker/k8s environments, where one of the descendants creates another process group thus making those processes out of reach through earlier `pgid`[1], there is not much we can do in Cloudprober itself. For k8s we'll recommend `shareProcessNamespace: true` for pod spec and for docker simply `--init` flag.
[1] - This happens with browser probe where playwright creates some chrome task, which in turn creates …
> [probes.command] Revert dedicated zombie reaper solutions

- probes/external/serverutils/serverutils.go
- Modify severutils to log probe options on timeout.
- Makes it possible to tell which instance of a probe timed out. The probeId is totally internal, so you can't map it to which probe failed without this.
> [probes.external] In server, log probe options on timeout

- probes/http/request.go
- probes/http/request_test.go
- Add a test that verifies that labels are added regardless of failures.
> [probes.http] Update target labels even if target resolution fails

- probes/external/external_server.go
Currently, if an external server probe writes a large debug log to stderr exceeding `bufio.MaxScanTokenSize`, cloudprober's stderr read loop will terminate.
For `server` probes (rather than ONCE probes), this is a bad failure mode since the child process will continue attempting to log and will back up the stderr pipe. Eventually all attempts to log will block, causing prober goroutines to build up and OOM.
Approach here specifically checks for `ErrTooLong` (I wanted to make sure we *do* still terminate when we hit an EOF-like error). But, consider this a strawman, an approach that checks for all EOF-like errors might be more robust.
@manugarg
> Continue reading upon ErrTooLong in external server probe stderr read loop

- examples/tls/cloudprober.cfg
* Include a tip for helm chart users to use`extraSecretMounts` to  acess cert from [kubenetes secrets](https://k8s.io/docs/concepts/configuration/secret/)
This implements https://github.com/cloudprober/cloudprober/issues/1079 and is a clean branch recreation of https://github.com/cloudprober/cloudprober/pull/1080
> Add an example config for a HTTP TLS probe
