probes/dns/dns.go

This is more representative of real traffic, which should not repeat
transaction IDs.

Generate a new DNS transaction ID for each probe

---

Dockerfile.buildx
Makefile

= Add a new Dockerfile for multiarch docker image.
= Add buildx support to Makefile.

Multi-arch docker image.

---

surfacers/probestatus/html_tmpl.go
surfacers/probestatus/probestatus.go
web/resources/header.go

= In preparation to merge /status and /probestatus, show  version, startup time on /probestatus page.
= Other minor style tweaks.

[probestatus] Show version, startup time as well.

---

probes/ping/ping.go

= Privileged IPv4 ping was broken on Linux (#122). For IPv4 RAW sockets, IP header is not stripped.
= If probe is IPv4, and incoming packet's first byte suggests that there is an IP header, assume that regardless of the OS. I think it's a safe assumption.

[ping] Fix privileged IPv4 ping (RAW socket).

---

.github/workflows/go.yml
probes/ping/ping_test.go

* Run real ping tests through Github actions to better discover and avoid issues like #122.

[ping] Run real ping tests through Github actions.

---

surfacers/probestatus/graph.go
surfacers/probestatus/graph_test.go
surfacers/probestatus/probestatus.go

= Add an option to override graph resolution through a URL param (graph_res).
= Allow selecting probes through URL params (?probe=ping_probe).

[probestatus] Refactor and improve.

---

surfacers/probestatus/html_tmpl.go
surfacers/probestatus/static/probestatus.css
surfacers/probestatus/static/probestatus.js

= Add buttons for graph_endtime and graph_duration parameters.
= Serve stylesheet through a different file.

[probestatus] Add buttons to control graph timeline.

---

targets/file/file.go

= Use targets' re_eval_sec to configure the RDS provider.
= Use fixed small refresh interval, time.Second, for refreshing the file's RDS client.

[targets][file] Fix file targets' re-eval strategy (See: #136).

---

probes/http/http.go
probes/http/http_test.go

= We had an option to disable HTTP2 but it was not getting enabled by default. Fix that.
= Use Go's default HTTP transport and override fields that we need to change.
= Add a test to verify the HTTP transport we create.

[http] Fix HTTP/2 behavior (see: #139).

---

rds/kubernetes/pods.go
rds/kubernetes/pods_test.go
rds/kubernetes/testdata/pods.json

= Also, update the tests to catch such bugs in the future.

[k8s rds] Fix the pods resources parsing bug (#150).

---

surfacers/surfacers.go
surfacers/surfacers_test.go

= Improve inferType tests and make them figure out if type infer logic is missing for some surfacer types.

[surfacers] Add type infer logic for probestatus.

---

probes/ping/icmpconn_unix.go

- SCM_TIMESTAMP control messages are only 8-byte on ARMv7. ARMv7 uses 4-byte `sec`, `usec` fields in the `timeval` struct [1].
- Handle the case where control message size is only 8 byte.
[1] - https://cs.opensource.google/go/go/+/master:src/runtime/defs_linux_arm.go;l=155;drc=9d34fc5108d91bfcce3c465069dbb2c563af4229

[ping] Fix for ARMv7.

---

surfacers/probestatus/html_tmpl.go
surfacers/probestatus/probestatus.go
surfacers/probestatus/static/probestatus.js
web/resources/header.go
web/static/cloudprober.css

* Add probe selectors to the status page.
* Reduce drop if no data interval to 6h (from 24h).

[status page] Further improve our status page.

---

cmd/cloudprober.go
common/httputils/httputils.go
common/httputils/httputils_test.go
examples/extensions/myprober/myprober.go
surfacers/probestatus/probestatus.go
surfacers/probestatus/probestatus_test.go
surfacers/surfacers.go
web/web.go

Plus some other safety changes.

[status page] Redirect "/" to "/status"

---

surfacers/probestatus/probestatus.go
surfacers/probestatus/probestatus_test.go

[status page] Fix page caching.

---

Makefile
cmd/cloudprober.go
config/runconfig/runconfig.go
web/resources/header.go

* Add build timestamp. Show it on the status page.
* If current binary was built from a git client with uncommitted changes, add "(dirty)" to the version string.

[buildinfo] Add more buildinfo.

---

surfacers/probestatus/dashboard.go
surfacers/probestatus/dashboard_test.go
surfacers/probestatus/probestatus.go
surfacers/probestatus/timeseries.go

Show per target status of data/no-data.

[status page] Improve status table.

---

probes/http/http.go

[probes.http] Initialize probe config with zero values if config is nil.

---

metrics/metrics.go
metrics/metrics_test.go

[probes.external] Parse negative numerical values as well.

---

probes/grpc/grpc_test.go

Also, while here, modernize the tests a bit.

[probes.grpc] Try to improve the test time.

---

logger/logger.go
logger/logger_test.go

* WithLabels should modify existing labels and should be able to work with empty logger.Logger.
* Also, add tests while here.

[logger] WithLabels should just add labels, and add tests

---

surfacers/cloudwatch/proto/config_proto_gen.cue
tools/gen_pb_go.sh

Regardless whether it's in the path or not.

[proto] Always download protoc.

---

Dockerfile
Dockerfile.dev
examples/surfacers/stackdriver_surfacer.cfg

* Also fix comment in the main Dockerfile.
* Fix example config.

[dev] Add a dockerfile for development and testing.

---

probes/grpc/grpc.go
probes/grpc/grpc_test.go

* Also, improve coverage overall for transport security configuration.

[probes.grpc] Add tests for the recently added function

---

common/oauth/bearer.go
common/oauth/bearer_test.go
common/oauth/http_token.go
common/oauth/oauth.go
common/oauth/proto/config.pb.go
common/oauth/proto/config.proto
common/oauth/proto/config_proto_gen.cue

[oauth] Let bearer token type handle JSON tokens.

---

probes/external/external.go

I haven't actually ran into any issue related to this, but from my reading it looks like access to `cmdRunning` should be synchronized

Synchronize access to cmdRunning

---

probes/http/http_test.go

= So far we only tested through a test transport. This PR adds tests
that use the default HTTP transport.

[probes.http] Add real HTTP request body tests.

---

probes/http/http.go
probes/http/http_test.go
probes/http/request.go
probes/http/request_test.go

[probes.http] Fix how we determine whether to change TLS config servername.

---

.github/workflows/go.yml
sonar-project.properties

This is to allow the use of test and coverage reports in Sonarcloud.

[build] Run Sonar scanner explicitly.

---

docs/config/_default/menus/menus.toml
docs/content/docs/overview/cloudprober/index.md
docs/content/docs/surfacers/_index.md
docs/content/docs/surfacers/cloudwatch.md
docs/content/docs/surfacers/overview.md
docs/content/docs/surfacers/stackdriver.md
docs/layouts/partials/sidebar/docs-menu.html

= Make menu titles clickable.
= Add ability to hide menu items.
= Hide unnecessary items.

[docs] Make sidebar menu better.

---

.github/workflows/hugo.yml
.gitignore
Makefile
docs/config/_default/menus/menus.toml
docs/content/docs/config/metrics.md
docs/content/docs/config/oauth.md
docs/content/docs/config/overview.md
docs/content/docs/config/probes.md
docs/content/docs/config/rds.md
docs/content/docs/config/servers.md
docs/content/docs/config/surfacer.md
docs/content/docs/config/targets.md
docs/content/docs/config/tlsconfig.md
docs/content/docs/config/validators.md
docs/content/docs/overview/cloudprober/index.md
docs/layouts/shortcodes/config-doc.html
docs/layouts/shortcodes/config-docs-nav.html

- I've been wanting to do this for so long. \o/
- Finally we have configuration documentation, automatically generated from the protobufs themselves.
- Documentation is generated using the new tool I created recently: https://github.com/manugarg/protodoc
- Moreover we generate the documentation for both the formats: yaml and textpb, and provide a way to switch between the two.

[docs] Configuration documentation, finally! Woohoo!!

---

docs/layouts/shortcodes/config-docs-nav.html
docs/static/configdoc.js

- Build ToC from the headings and add it to the ToC div.
- Also, auto-generate the top, inter-package navigation.

[docs.config] Add ToC to the config documentation pages.

---

docs/static/configdoc.js

= Disable headings in the hidden div.
= Add ":disabled" to the heading's ids in the hidden div, otherwise we end up with two elements having same id.

[docs] Fix anchor links handling.

---

docs/content/docs/surfacers/overview.md
docs/content/docs/surfacers/stackdriver.md
docs/static/configdoc.js
surfacers/internal/stackdriver/proto/config.pb.go
surfacers/internal/stackdriver/proto/config.proto
surfacers/internal/stackdriver/proto/config_proto_gen.cue
surfacers/internal/stackdriver/stackdriver.go

= Also fix a bug in the new config documentation ToC functionality.

[surfacers.doc] Fix surfacers documentation links.

---

probes/external/external_test.go

On Windows, if we exit the test before test executable stops running, we get an error like this:
go: remove C:\Users\manugarg\AppData\Local\Temp\go-build1161854330\b001\external.test.exe: Access is denied.
Note: TestProbeStartCmdIfNotRunning test uses test executable itself as the probe command.

[probes.external] Wait for command exit before exiting the test.

---

docs/content/docs/how-to/alerting/index.md

[alerting] Update alerting doc

---

docs/content/docs/about/index.md

- I think it reads better now.

[about] Update the about page.

---

README.md
docs/assets/scss/common/_custom.scss
docs/layouts/index.html

- Fix font color of the companies' list. Dark colors don't work in dark mode.
- Add a link to 'about' page on the github homepage.

[docs] Improve documentation

---

cloudprober.go
cloudprober_test.go

- Use read-write mutex, instead of regular mutex, to control access to cloudprober config info.
- Get raw and parsed config from the config source directly instead of storing it ahead of time.
- Allow access to the prober instance.

[prober] Minor refactoring.

---

Dockerfile.dev

* Update golang
* Update location of cloudprober_test.cfg

Fix Dockerfile.dev

---

surfacers/internal/otel/otel.go
surfacers/internal/otel/proto/config.pb.go
surfacers/internal/otel/proto/config.proto
surfacers/internal/otel/proto/config_proto_gen.cue

- You can use this for example to specify a project id or team id.

[surfacers.otel] Additional resource attribute support.

---

probes/external/external.go

Also, don't log pipe closed errors for stdout and stderr reading.

[probes.external] Increase max scanner token size to 256kB (from 64kB).

---

probes/grpc/grpc.go

grpcurl's BlockingDial provides better error message on connection failure.

[probes.grpc] Use grpcurl's blocking dial

---

probes/grpc/grpc.go

- Also, update result during connection success too.

[probes.grpc] Run validators only if probe succeeded.

---

probes/external/external_server.go

Currently there is a logical race condition as follows:
Suppose there is an external probe running in SERVER mode, with only one `target`.
1) cloudprober [sends the single request](https://github.com/cloudprober/cloudprober/blob/d4bfee74f61d59e79c043da3dd030ad6bcdc7f27/probes/external/external_server.go#L268)
2) If the external probe server responds quickly enough, cloudprober can [read the reply](https://github.com/cloudprober/cloudprober/blob/d4bfee74f61d59e79c043da3dd030ad6bcdc7f27/probes/external/external_server.go#L224), but then when it [checks](https://github.com/cloudprober/cloudprober/blob/d4bfee74f61d59e79c043da3dd030ad6bcdc7f27/probes/external/external_server.go#L249) `sendDoneCh`, it might not be closed yet.
3) cloudprober's reader go-routine goes back to blocking on the …

Fix logical race condition in external server probe handling

---

validators/validators.go

Add a public validators package to provide extension probes an easy way to run validators.

[validators] Public validators package

---

docs/config/_default/menus/menus.toml
docs/content/docs/how-to/_index.md
docs/content/docs/how-to/built-in-servers.md
docs/content/docs/how-to/extensions.md
docs/content/docs/how-to/list/index.md

- Added a new list page for the how-to section
- Make 'GET STARTED' main menu item a drop down.

[docs] Docs navigation improvements:

---

docs/layouts/index.html

- Add newly identified organizational users.
- Add a more visible link to about page and github.
- Increase image size to be more assertive.

[homepage] Update homepage.

---

docs/config/_default/menus/menus.toml
docs/layouts/index.html

* Combine the 'about' and 'connect' menu items.
* Change sizes of subtitle and tagline.
* Increase vertical padding around the tagline

[homepage] Minor style changes.

---

internal/servers/http/http.go
internal/sysvars/sysvars.go
internal/sysvars/sysvars_test.go
prober/prober.go
probes/grpc/grpc.go
probes/udp/udp.go
surfacers/internal/cloudwatch/cloudwatch.go
surfacers/internal/pubsub/pubsub.go

- Introduce a new method GetVar which logs an error if sysvars is not
initialized or variable is not found.
- Use this new method to get "hostname" and "instance" in other pakages.
- Vars() will be used where we don't expect any specific variable, we're
just getting all the variables.
- Add a bunch of missing tests.

[sysvars] Improve sysvars package.

---

probes/common/sched/sched_test.go
probes/external/external_test.go
probes/grpc/grpc_test.go
probes/http/http_test.go
probes/options/options.go
probes/options/options_test.go
probes/ping/cmd/ping.go

- Make defining LogMetrics completely optional.

[options] Change how LogMetrics is implemented.

---

.gitignore

This is needed for some dev work[1] I am doing.
[1] Experimenting with playwright for browser testing.

[dev] Ignore node_modules everywhere

---

probes/browser/browser.go
probes/browser/tests/demo-todo-app.spec.ts
probes/browser/tests/test.spec.ts

Now that we have factored out command execution part (#854), we should use that.

[probes] Use common command execution functionality.

---

probes/http/http.go

Previously latency breakdown was calculated from probe start time, which means that all those metrics were basically accumulative. This change separates latency of each stage.

[probes.http] Make latency breakdown more accurate

---

internal/sysvars/sysvars.go
logger/logger.go

See https://github.com/cloudprober/cloudprober/issues/868 for some background.

[sysvars] In error messages, tell how to skip cloud metadata

---

docs/content/docs/how-to/targets/index.md

Loose end following https://github.com/cloudprober/cloudprober/pull/832

Cleanup dangling rds/ reference, which should be internal/rds

---

config/config.go
config/config_test.go
config/configsource.go
config/configsource_test.go
config/testdata/cloudprober_tmpl.cfg

- Also make a defaultConfigSource fields private. They are not accessed by another package.

[config] Make BaseVars and Sysvars cumulative

---

probes/http/cmd/http.go

Make sure options are initialized properly.

[probes.http] Fix the http probe binary

---

probes/browser/browser.go
probes/dns/dns.go
probes/dns/dns_test.go
probes/tcp/tcp.go
probes/tcp/tcp_test.go

Cleanup scheduler interface usage after #967.

[probes] Cleanup scheduler interface usage after #967

---

probes/http/http_test.go

This is a direct copy of @cbroglie's code here:
https://github.com/cloudprober/cloudprober/issues/872#issuecomment-2518722867

[probes.http] Add a test to verify that disabling http2 works

---

web/resources/header.go
web/resources/header_test.go
web/web.go
web/web_test.go

[web] Restructure header links and add link to artifacts page

---

surfacers/internal/probestatus/html_tmpl.go
surfacers/internal/probestatus/probestatus.go
web/resources/header.go
web/resources/header_test.go
web/web.go
web/web_test.go

See #1024 for the description of the problem this PR solves.

[web] Fix links for cases when serving behind reverse-proxy with non-root path mapping

---

surfacers/internal/probestatus/probestatus.go

- Even though server redirect is slightly better, it doesn't work if cloudprober is being served at a non-root URL through a reverse-proxy. For example, if cloudprober UI is exposed through a reverse-proxy at _http://mydomain:9313/prober/_, redirecting `/` to `/status` through server redirect will redirect the browser to _http://mydomain:9313/status_, while we actually want to go to: _http://mydomain:9313/prober/status_.
- This can be solved by using HTML's `<meta http-equiv=refresh .. url="[target-url]">` tag.
See #1024 for a description of the issue encountered without this change.

[web] Use HTML redirects for redirects

---

probes/udp/udp.go

- Worker should be added to worker group right before we start the worker. I missed this regression while reviewing [this change](https://github.com/cloudprober/cloudprober/commit/8595cc7576dc24d24eda4c316553c5224fcf43d8#diff-60308817fdc384b392de717262115b1287d368f4343a72664fbf0b715111ed5e).
- Also, use the newer (and better) way to resolve targets, where we call resolve on the endpoint itself. This way we can return the stored IP immediately instead of going back to target's resolver.
This fixes https://github.com/cloudprober/cloudprober/issues/1030. Much thanks to @Koaxiel for finding and debugging this bug.
Thinking more about it, we should perhaps change Targets' interface to not include Resolve at all, instead always store IP in the endpoint while discovering targets. I'll file …

[probes.udp] Bug-fix: don't add worker to working group prematurely

---

surfacers/internal/probestatus/graph.go

[status.graph] Don't try to graph NaN values

---

probes/udp/udp.go

- While processing packets, we were not updating highest sequence number when processing sent packets from the last packet processing cycle, this was causing some received packets to be punted for very long. This resulted in zigzag metrics, where success ratio unnecessarily jumped around 1.
- Graph after the fix:

[probes.udp] Fix a bug in packets processing

---

surfacers/internal/probestatus/html_tmpl.go
surfacers/internal/probestatus/static/probestatus.js

- Fix cloudprober.css link while serving on non-standard path.
- Also fix a small bug in javascript.

[web.status] Fix a CSS link for the status page.

---

docs/content/_index.md
docs/layouts/index.html
docs/package-lock.json
docs/package.json

- In the top left corner, show Cloudprober's description instead of just saying 'Cloudprober'.

[docs] Update leadline on cloudprober's homepage

---

examples/include/cloudprober.cfg
examples/include/cloudprober.d/team1.cfg
examples/include/cloudprober.d/team2.cfg
examples/include/cloudprober.d/vars.cfg

- Add some inline explanation.
- Demonstrate nested includes.

[examples.include] Expand include example

---

surfacers/internal/common/transform/transform_test.go

[surfacers.transform] Add test for CumulativeToGauge

---

docs/config/_default/menus/menus.toml
docs/layouts/index.html

- Make the title bigger (h2->h1)
- Add View on Github button
- Add icons for various features
- Make trusted-by logos slightly smaller.
I think overall these changes improve the hierarchy.

[docs] Some changes to the homepage.
